export { default as CUCEI } from './CUCEI.png';
export { default as exit } from './exit.png';
export { default as exitBlack } from './exitBlack.png';
export { default as eye } from './eye.png';
export { default as googleIcon } from './googleIcon.png';
export { default as messages } from './messages.png';
export { default as messagesBlack } from './messagesBlack.png';
export { default as notifications } from './notifications.png';
export { default as search } from './search.png';
export { default as send } from './send.png';
export { default as settings } from './settings.png';
export { default as settingsBlack } from './settingsBlack.png';
export { default as star } from './star.png';
export { default as user } from './user.png';
export { default as fondo } from './fondo.png';
export { default as imagen1 } from './Imagen1.png';
export { default as starSinF } from './starSinF.png';
export { default as newButtton } from './new.png'
export { default as newFocus } from './new-focus.png'
export { default as allPosts } from './allPosts.png'
export { default as save } from './save.png'